[package]
name = "geo-marching-squares"
version = "0.1.0"
edition = "2021"

[dependencies]
geojson = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.10"
geo = "0.28"
arrayvec = "0.7"
